version: '3.7'

volumes:
  logs:
    driver: local

services:
  php:
    build:
      context: ./
      dockerfile: ./build/php.docker
    container_name: "${PROJECT_NAME}_php"
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public public/index.php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
      - ./build/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
