index:
    path: /
    controller: App\Controller\Main::index

creational.methodFactory:
    path: creational/methodFactory
    controller: App\Controller\Creational::methodFactory

creational.abstractFactory:
    path: creational/abstractFactory
    controller: App\Controller\Creational::abstractFactory

creational.builder:
    path: creational/builder
    controller: App\Controller\Creational::builder

creational.prototype:
    path: creational/prototype
    controller: App\Controller\Creational::prototype

creational.singleton:
    path: creational/singleton
    controller: App\Controller\Creational::singleton



structural.adapter:
    path: structural/adapter
    controller: App\Controller\Structural::adapter

structural.most:
    path: structural/most
    controller: App\Controller\Structural::most

structural.composite:
    path: structural/composite
    controller: App\Controller\Structural::composite

structural.decorator:
    path: structural/decorator
    controller: App\Controller\Structural::decorator

structural.fasad:
    path: structural/fasad
    controller: App\Controller\Structural::fasad

structural.flyweight:
    path: structural/flyweight
    controller: App\Controller\Structural::flyweight

structural.proxy:
    path: structural/proxy
    controller: App\Controller\Structural::proxy


behavioral.cor:
    path: behavioral/cor
    controller: App\Controller\Behavioral::cor