index:
    path: /
    controller: App\Controller\Main::index

creational.methodFactory:
    path: creational/methodFactory
    controller: App\Controller\Creational::methodFactory

creational.abstractFactory:
    path: creational/abstractFactory
    controller: App\Controller\Creational::abstractFactory

creational.builder:
    path: creational/builder
    controller: App\Controller\Creational::builder

creational.prototype:
    path: creational/prototype
    controller: App\Controller\Creational::prototype

creational.singleton:
    path: creational/singleton
    controller: App\Controller\Creational::singleton