index:
    path: /
    controller: App\Controller\Main::index

creational.methodFactory:
    path: creational/methodFactory
    controller: App\Controller\Creational::methodFactory

creational.abstractFactory:
    path: creational/abstractFactory
    controller: App\Controller\Creational::abstractFactory

creational.builder:
    path: creational/builder
    controller: App\Controller\Creational::builder

creational.prototype:
    path: creational/prototype
    controller: App\Controller\Creational::prototype

creational.singleton:
    path: creational/singleton
    controller: App\Controller\Creational::singleton



structural.adapter:
    path: structural/adapter
    controller: App\Controller\Structural::adapter

structural.most:
    path: structural/most
    controller: App\Controller\Structural::most

structural.composite:
    path: structural/composite
    controller: App\Controller\Structural::composite

structural.decorator:
    path: structural/decorator
    controller: App\Controller\Structural::decorator

structural.fasad:
    path: structural/fasad
    controller: App\Controller\Structural::fasad

structural.flyweight:
    path: structural/flyweight
    controller: App\Controller\Structural::flyweight

structural.proxy:
    path: structural/proxy
    controller: App\Controller\Structural::proxy



behavioral.cor:
    path: behavioral/cor
    controller: App\Controller\Behavioral::cor

behavioral.command:
    path: behavioral/command
    controller: App\Controller\Behavioral::command

behavioral.iterator:
    path: behavioral/iterator
    controller: App\Controller\Behavioral::iterator

behavioral.mediator:
    path: behavioral/mediator
    controller: App\Controller\Behavioral::mediator

behavioral.memento:
    path: behavioral/memento
    controller: App\Controller\Behavioral::memento

behavioral.observer:
    path: behavioral/observer
    controller: App\Controller\Behavioral::observer

behavioral.state:
    path: behavioral/state
    controller: App\Controller\Behavioral::state

behavioral.strategy:
    path: behavioral/strategy
    controller: App\Controller\Behavioral::strategy

behavioral.templateMethod:
    path: behavioral/template-method
    controller: App\Controller\Behavioral::templateMethod